version: '3'

services:
  antink-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: antink-server:latest
    container_name: antink-server
    command: server
    privileged: true
    volumes:
      - ./it24_host:/it24_host:rw
      - antink_mount:/antink_mount
      - antink-logs:/antink-logs
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped

  antink-logger:
    build:
      context: .
      dockerfile: Dockerfile
    image: antink-logger:latest
    container_name: antink-logger
    command: logger
    volumes:
      - antink-logs:/antink-logs
    depends_on:
      - antink-server
    restart: unless-stopped

volumes:
  antink_mount:
  antink-logs:
